# This is a basic workflow to help you get started with Actions

name: Clipster

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Python deps
        run: pip install pycodestyle pylint

      - name: Install deps
        run: sudo apt-get install ibus python3-gi python-gobject gir1.2-glib-2.0 gir1.2-ibus-1.0 libwnck-3-0 gir1.2-wnck-3.0 libgtk-3-0 gir1.2-gtk-3.0 xvfb

      - name: Run Tests
        run: xvfb-run ./tests/test.sh
